server:
  port: 80
spring:
  application:
    name: customer-order
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181 #需要启动zookeeper服务器，在zookeeper中使用ls / 查看节点
      #connect-string: 127.0.0.1:2181,127.0.0.1:2182 #集群