server:
  port: 8004
spring:
  application:
    name: provider-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181 #需要启动zookeeper服务器，在zookeeper中使用ls / 查看节点
#      connect-string: 127.0.0.1:2181,127.0.0.1:2182 #集群